version: '3'

services:
  listing_body:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  database:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
